name: transmit
version: 1.9.0
author: Paul VanKeuren <paul.vankeuren@gmail.com>
description: A dart package that allows for quick event passing between distinct parts of your codebase.

environment:
  sdk: '>=1.0.0 <2.0.0'
