name: transmit
version: 1.0.1
author: Paul VanKeuren <paul.vankeuren@gmail.com>
description: A dart package that allows for quick event passing between distinct parts of your codebase.

dev_dependencies:
  build_runner: '>=0.8.10 <0.10.0'
  build_web_compilers: '>=0.3.6 <0.5.0'