name: pump
version: 2.0.0
author: Paul VanKeuren <paul.vankeuren@gmail.com>
description: A dart package that allows for the creation of event-like objects, and the Services that consume them.
dev_dependencies:
  browser: any
