name: pump
version: 0.0.2
author: Paul VanKeuren <paul.vankeuren@gmail.com>
description: |-
  A dart package for the Pump class.
  Allows for the pumping and filtering of events using a publish subscribe model.
dev_dependencies:
  browser: any
